<?php
include 'conne.php';

$result = mysqli_query($sql_con, "SELECT * FROM `social`");
while ($row = mysqli_fetch_array($result)) {
   $Facebook = $row['Facebook'];
   $twitter = $row['Twitter'];
   $Instagram = $row['Instagram'];
   $linkedin = $row['LinkedIn'];
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <title>Term of use || Appanage-mart</title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!--enable mobile device-->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!--fontawesome css-->
   <link rel="stylesheet" href="css/font-awesome.min.css">
   <!--bootstrap css-->
   <link rel="stylesheet" href="css/bootstrap.min.css">
   <!--animate css-->
   <link rel="stylesheet" href="css/animate-wow.css">
   <!--main css-->
   <link rel="stylesheet" href="css/style.css">
   <link rel="icon" type="image/png" href="images/AppanageLogo2.png">
   <link rel="stylesheet" href="css/bootstrap-select.min.css">
   <link rel="stylesheet" href="css/slick.min.css">
   <!--responsive css-->
   <link rel="stylesheet" href="css/responsive.css">
</head>

<body>
   <?php include 'header.php'; ?>
   <!-- Modal -->
   <div class="modal fade lug" id="myModal" role="dialog">
      <div class="modal-dialog">
         <!-- Modal content-->
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title">Change</h4>
            </div>
            <div class="modal-body">
               <ul>
                  <li><a href="#"><img src="images/flag-up-1.png" alt="" /> United States</a></li>
                  <li><a href="#"><img src="images/flag-up-2.png" alt="" /> France </a></li>
               </ul>
            </div>
         </div>
      </div>
   </div>
   <div class="terms-conditions" style="margin-top: 5rem;">
      <div class="container">
         <div class="row">
            <div class="col-md-12">
               <div class="terms-box">
                  <h2 style="color:var(--brandColor);text-align: center;">Terms and Conditions</h2>
                  <p style="font-weight: 600;">This document is an electronic record in terms of the amended Information Technology Act, 2000 and rules and regulation made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the Terms for access or usage of Just Dial’s service via Just Dial Portal. This document meets the stipulations and conditions mentioned in Section 65B (2) of the Indian Evidence Act, 1872.
                  </p>
                  <p><strong>YOUR ACCEPTANCE OF THIS AGREEMENT:</strong> This is an agreement between you ("you" or "your") and Just Dial Limited, a company incorporated under the Companies Act 1956 with its registered office at Building M, 501-B, Palm Court Complex, Besides Goregaon Sports Club, New Link Road, Malad (W), Mumbai 400 064 ("Just Dial" "we," or "our") that governs your use of the search services offered by Just Dial through its website www.justdial.com ("Website"), telephone search, SMS, WAP or any other medium using which Just Dial may provide the search services (collectively "Platforms" ). When you access or use any of the Platforms you agree to be bound by these Terms and Conditions ("Terms").
                  </p>
                  <p><strong>CHANGES:</strong> We may periodically change the Terms and the Site without notice, and you are responsible for checking these Terms periodically for revisions. All amended Terms become effective upon our posting to the Site, and any use of the site after such revisions have been posted signifies your consent to the changes.
                  </p>
                  <p><strong>HOW YOU MAY USE OUR MATERIALS:</strong> We use a diverse range of information, text, photographs, designs, graphics, images, sound and video recordings, animation, content, advertisement and other materials and effects (collectively "Materials") for the search services on the Platforms. We provide the Material through the Platforms FOR YOUR PERSONAL AND NON-COMMERCIAL USE ONLY.</p>

                  <p>While every attempt has been made to ascertain the authenticity of the Platforms content, Just Dial is not liable for any kind of damages, losses or action arising directly or indirectly, due to access and/or use of the content in the Platforms including but not limited to decisions based on the content in the Platforms which results in any loss of data, revenue, profits, property, infection by viruses etc.</p>

                  <p>Accordingly, you may view, use, copy, and distribute the Materials found on the Platforms for internal, non-commercial, informational purposes only. You are prohibited from data mining, scraping, crawling, or using any process or processes that send automated queries to Just Dial.. You may not use the Platforms or any of them to compile a collection of listings, including a competing listing product or service. You may not use the Platforms or any Materials for any unsolicited commercial e-mail. Except as authorized in this paragraph, you are not being granted a license under any copyright, trademark, patent or other intellectual property right in the Materials or the products, services, processes or technology described therein. All such rights are retained by Just Dial, its subsidiaries, parent companies, and/or any third party owner of such rights.</p>

                  <p><strong>HOW YOU MAY USE OUR MARKS:</strong> The Just Dial company names and logos and all related products and service names, design marks and slogans are trademarks and service marks owned by and used under license from Just Dial or it's wholly owned subsidiaries. All other trademarks and service marks herein are the property of their respective owners. All copies that you make of the Materials on any of the Platforms must bear any copyright, trademark or other proprietary notice located on the respective Platforms that pertains to the material being copied. You are not authorized to use any Just Dial name or mark in any advertising, publicity or in any other commercial manner without the prior written consent of Just Dial. Requests for authorization should be made to intproperty@justdial.com</p>

                  <p><strong>HOW WE MAY USE INFORMATION YOU PROVIDE TO US:</strong> Do not send us any confidential or proprietary information. Except for any personally identifiable information that we agree to keep confidential as provided in our Privacy Policy, any material, including, but not limited to any feedback, data, answers, questions, comments, suggestions, ideas or the like, which you send to us will be treated as being non-confidential and nonproprietary. We assume no obligation to protect confidential or proprietary information (other than personally identifiable information) from disclosure and will be free to reproduce, use, and distribute the information to others without restriction. We will also be free to use any ideas, concepts, know-how or techniques contained in information that you send us for any purpose whatsoever including but not limited to developing, manufacturing and marketing products and services incorporating such information.</p>

               </div>
            </div>
            <div class="col-md-12">
               <div class="terms-box">
                  <h3>REVIEWS, RATINGS & COMMENTS BY USERS:</h3>
                  <p>Since, Just Dial provides information directory services through various mediums (SMS, WAP, E-Mail, Website, APP and voice or phone), your ("Users") use any of the aforementioned medium to post Reviews, Ratings and Comments about the Just Dial services and also about the Advertiser's listed at Just Dial is subject to additional terms and conditions as mentioned herein.
                  </p>
                  <p>You are solely responsible for the content of any transmissions you make to the Site or any transmissions you make to any mediums offered by Just Dial and any materials you add to the Site or add to any mediums offered by Just Dial, including but not limited to transmissions like your Reviews, Ratings & Comments posted by you(the "Communications"). Just Dial does not endorse or accept any of your Communication as representative of their (Just Dial) views. By transmitting any public Communication to the Site, you grant Just Dial an irrevocable, non-exclusive, worldwide, perpetual, unrestricted, royalty-free license (with the right to sublicense) to use, reproduce, distribute, publicly display, publicly perform, adapt, modify, edit, create derivative works from, incorporate into one or more compilations and reproduce and distribute such compilations, and otherwise exploit such Communications, in all Platforms now known or later developed.
                  </p>
                  <p>You confirm and warrant that you have the right to grant these rights to Just Dial . You hereby waive and grant to Just Dial all rights including intellectual property rights and also "moral rights" in your Communications, posted at Just Dial through any of mediums of Just Dial. Just Dial is free to use all your Communications as per its requirements from time to time. You represent and warrant that you own or otherwise control all of the rights to the content that you post as Review, Rating or Comments; that the content is accurate; that use of the content you supply does not violate these Terms and will not cause injury to any person or entity. For removal of doubts it is clarified that, the reference to Communications would also mean to include the reviews, ratings and comments posted by your Friend's tagged by you. Also Just Dial reserves the right to mask or unmask your identity in respect of your Reviews, Ratings & Comments posted by you.
                  </p>
                  <p>It is also clarified that, if there are any issues or claims due to your posts by way of Reviews, Ratings and Comments, then Just Dial reserves right to take appropriate legal action against you. Further, you shall indemnify and protect Just Dial against such claims or damages or any issues, due to your posting of such Reviews, Ratings and Comments Just Dial takes no responsibility and assumes no liability for any content posted by you or any third party on Just Dial site or on any mediums of Just Dial.
                  </p>
                  <p>You further acknowledge that conduct prohibited in connection with your use of the Forums includes, but is not limited to, breaching or attempting to breach the security of the Site or any of the mediums of Just Dial.</p>
               </div>
            </div>
            <div class="col-md-12">
               <div class="terms-box">
                  <h3>Disclaimer</h3>
                  <p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and coditions relating to our website and the use of this website(including, without limitation, any
                     warranties implied by law in respect of satisfactory wuality, fitness for purpose and/or the use of reasonable care and skill). Nothing in disclaimer will:
                  </p>
                  <p>limit or exclude our or your liability for death or personal injury resulting from negligence;
                     limit or exclude our or your liability for fraud or fraudulent misrepresentation;<br>
                     limit any of our or your liabilities that may not be excluded under applicable low; or<br>
                     exclude any of our or your liabilities that may not be excluded under applicable law.<br>
                     The limitations and exclusions of liability set out in this Section and elswhere in this disclaimer:(a) are subject to the paragraph; and (b) govern all liabilities arising under the disclaimer<br>
                     or in relation to the subject matter of this disclaimer, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty.
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
   <?php include 'footer.php'; ?>
   <!--main js-->
   <script src="js/jquery-1.12.4.min.js"></script>
   <!--bootstrap js-->
   <script src="js/bootstrap.min.js"></script>
   <script src="js/bootstrap-select.min.js"></script>
   <script src="js/slick.min.js"></script>
   <script src="js/select2.full.min.js"></script>
   <script src="js/wow.min.js"></script>
   <!--custom js-->
   <script src="js/custom.js"></script>
</body>

</html>